region        = "ap-southeast-2"
namespace     = "snippets"
environment   = "personal"
stage         = "prod"
function_name = "example-hello-world"
handler       = "handler.lambda_handler"
runtime       = "python3.7"
filename      = "handler.py"
