#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo "======= running terraform validate before committing ======="

for d in */; do
    (cd "$d" && terraform validate)
    if [[ $? -ne 0 ]]; then
        exit 1
    else
        echo "terraforms file valid"
    fi
done;

